/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fdf8ff',
        'surface-dim': '#ddd8e6',
        'surface-bright': '#fdf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f1ff',
        'surface-container': '#f1ebfa',
        'surface-container-high': '#ebe6f4',
        'surface-container-highest': '#e5e0ef',
        'on-surface': '#1c1a24',
        'on-surface-variant': '#484556',
        'inverse-surface': '#312f3a',
        'inverse-on-surface': '#f4eefd',
        outline: '#797588',
        'outline-variant': '#c9c4d9',
        'surface-tint': '#5d37ee',
        primary: '#542ae6',
        'on-primary': '#ffffff',
        'primary-container': '#6d4cff',
        'on-primary-container': '#f5f0ff',
        'inverse-primary': '#c9bfff',
        secondary: '#6934dc',
        'on-secondary': '#ffffff',
        'secondary-container': '#8353f6',
        'on-secondary-container': '#fffbff',
        tertiary: '#575656',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6f6e6e',
        'on-tertiary-container': '#f5f1f1',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e5deff',
        'primary-fixed-dim': '#c9bfff',
        'on-primary-fixed': '#1a0063',
        'on-primary-fixed-variant': '#4403d8',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#cfbdff',
        'on-secondary-fixed': '#22005d',
        'on-secondary-fixed-variant': '#530dc6',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474646',
        background: '#fdf8ff',
        'on-background': '#1c1a24',
        'surface-variant': '#e5e0ef',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        'container-max': '1280px',
        'section-padding': '80px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'soft': '0px 4px 20px rgba(0, 0, 0, 0.03)',
        'elevated': '0px 12px 32px rgba(0, 0, 0, 0.08)',
        'hover': '0px 8px 32px rgba(0, 0, 0, 0.15)',
      },
    },
  },
  plugins: [],
}
